---
language: perl

os:
  - linux
  # - osx

arch:
  - amd64
  - ppc64le
  - s390x
  # - arm64	# Gets 404 error

env:
  - AUTOMATED_TESTING=1
  - PERL_CPANM_OPT="--notest --force --skip-satisfied"

perl:
  - 5.32-shrplib
  - 5.30-shrplib
  - 5.28-shrplib
  - 5.26-shrplib
  - 5.24-shrplib

sudo: false

before_install:
  # - sudo apt-get update -q
  # - sudo apt-get install sqlite3 libdbi-perl libdbd-sqlite3-perl
  - cpanm -qin --skip-satisfied Devel::Cover Devel::Cover::Report::Coveralls Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Most Test::CleanNamespaces Test::NoWarnings Test::Warn

install:
  - cpanm -qin --skip-satisfied --installdeps --notest .

script:
  perl Makefile.PL && make && cover -test -report coveralls

jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      install:
        - cpanm --notest --installdeps .
      script:
        - perl Makefile.PL
        - gmake
        - gmake test
