language: perl
os:
  - linux
  # - osx

perl:
  # - "5.22"	# Coro is broken on this - but Coro is still better than threads
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  # - "5.12"

install:
  - cpanm -n Devel::Cover Devel::Cover::Report::Coveralls Test::Script Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Most Test::CleanNamespaces Test::NoWarnings
  - cpanm -v --installdeps --notest .

script:
  perl Makefile.PL && make && cover -test -report coveralls
