language: perl
os:
  - linux
  # - osx

perl:
  - "5.22-extras"
  - "5.20-extras"
  - "5.18-extras"
  - "5.16-extras"
  - "5.14-extras"
  - "5.12-extras"

before_install:
  cpanm -n Devel::Cover Devel::Cover::Report::Coveralls Test::Script Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Most Test::CleanNamespaces Test::NoWarnings

install:
  - cpanm -v --installdeps --notest .

script:
  perl Makefile.PL && make && cover -test -report coveralls
