language: perl
os:
  - linux
  # - osx

perl:
  - "5.22-thr"
  - "5.20-thr"
  - "5.18-thr"
  - "5.16-thr"
  - "5.14-thr"
  - "5.12-thr"

before_install:
  cpanm -n Devel::Cover::Report::Coveralls Test::Script Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Most Test::CleanNamespaces Test::NoWarnings

install:
  - cpanm -v --installdeps --notest .

script:
  perl Makefile.PL && make && cover -test -report coveralls
